### ISSUE TITLE
Problem when trying to upload file

### ISSUE THREAD

**Issue by techguydev** [JasonMillward/laravel-dropzone#3]
Hi

Thanks a lot for sharing this code.

Is there any special configuration related to permission that needs to be set on amazon s3 bucket?, I am tying to upload and it does not work

I am able to generate the special signed url but once it tries to publish it in s3 it stops and no error is returned

**Comment by JasonMillward** [comment]
Thank you for bringing this to my attention, I'm sure it's failing on the CORS checking. 

So all you need to do is add in this CORS config to the S3 bucket. When using in production you'll want to change `AllowedOrigin` to your domain instead of leaving it open for development.

```
<?xml version="1.0" encoding="UTF-8"?>
<CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
    <CORSRule>
        <AllowedOrigin>*</AllowedOrigin>
        <AllowedMethod>GET</AllowedMethod>
        <AllowedMethod>PUT</AllowedMethod>
        <AllowedMethod>POST</AllowedMethod>
        <AllowedMethod>DELETE</AllowedMethod>
        <MaxAgeSeconds>3000</MaxAgeSeconds>
        <ExposeHeader>Access-Control-Allow-Origin</ExposeHeader>
        <AllowedHeader>*</AllowedHeader>
    </CORSRule>
</CORSConfiguration>
```
